name: Publicar Diagramas Mermaid

on:
  push:
    branches:
      - main
    paths:
      - '**.mmd'
      - 'site/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copiar arquivos para pasta pública
        run: |
          mkdir -p public
          cp -r site/* public/
          cp -r arquitetura public/
          cp -r bd public/

      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
