name: Publicar diagramas Mermaid

on:
  push:
    branches:
      - main
    paths:
      - 'arquitetura/diagramas/*.mmd'
      - 'bd/diagramas/*.mmd'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências do Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Instalar Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Criar pastas de saída
        run: mkdir -p public/arquitetura public/bd

      - name: Gerar SVGs dos diagramas
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
        run: |
          for file in arquitetura/diagramas/*.mmd; do
            npx mmdc -i "$file" -o "public/arquitetura/$(basename "$file" .mmd).svg"
          done
          for file in bd/diagramas/*.mmd; do
            npx mmdc -i "$file" -o "public/bd/$(basename "$file" .mmd).svg"
          done

      - name: Gerar index.html
        run: |
          echo "<html><head><title>Diagramas do Projeto</title></head><body><h1>Diagramas do Projeto</h1>" > public/index.html
          echo "<h2>Arquitetura</h2>" >> public/index.html
          for svg in public/arquitetura/*.svg; do
            echo "<div><h3>$(basename $svg)</h3><img src='arquitetura/$(basename $svg)' style='max-width:100%;border:1px solid #ccc;'></div>" >> public/index.html
          done
          echo "<h2>Banco de Dados</h2>" >> public/index.html
          for svg in public/bd/*.svg; do
            echo "<div><h3>$(basename $svg)</h3><img src='bd/$(basename $svg)' style='max-width:100%;border:1px solid #ccc;'></div>" >> public/index.html
          done
          echo "</body></html>" >> public/index.html

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
